# Generated by Django 3.2.4 on 2023-08-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='Tel',
        ),
    ]
